#include "fullchain.h"

const char fullchain_pem[] = "-----BEGIN CERTIFICATE-----\n"
                             "MIIDljCCAxygAwIBAgISBllpdazP9WxR3go4NhuYqiUsMAoGCCqGSM49BAMDMDIx\n"
                             "CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF\n"
                             "ODAeFw0yNTEwMzEwOTA1MTdaFw0yNjAxMjkwOTA1MTZaMB8xHTAbBgNVBAMTFG90\n"
                             "YS5zaW5hdW5nb2RpbmcuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/8dw\n"
                             "UKIavBAWmYGHZqxyQ38TrTeORJe+1gBJdRtLwmubLJpyWc/Q8fy/ss5MoUn7DY9I\n"
                             "XVpj3gu6OD9mK3AluaOCAiMwggIfMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAU\n"
                             "BggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUxN0p\n"
                             "SmMdQPfbB3nIvA2JniFXmCkwHwYDVR0jBBgwFoAUjw0TovYuftFQbDMYOF1ZjiNy\n"
                             "kcowMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAChhZodHRwOi8vZTguaS5sZW5j\n"
                             "ci5vcmcvMB8GA1UdEQQYMBaCFG90YS5zaW5hdW5nb2RpbmcuY29tMBMGA1UdIAQM\n"
                             "MAowCAYGZ4EMAQIBMC0GA1UdHwQmMCQwIqAgoB6GHGh0dHA6Ly9lOC5jLmxlbmNy\n"
                             "Lm9yZy80NS5jcmwwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdgDLOPcViXyEoURf\n"
                             "W8Hd+8lu8ppZzUcKaQWFsMsUwxRY5wAAAZo5uSo9AAAEAwBHMEUCIQDPs+wG+HvB\n"
                             "jNmWIFkfENxEJjXg183ZjJOlOT0XXVwD2QIgaQryrpv38jN5XK7qCBmEJ4/YWv3Y\n"
                             "Y3bqU6OZXUHzPUsAdwCWl2S/VViXrfdDh2g3CEJ36fA61fak8zZuRqQ/D8qpxgAA\n"
                             "AZo5uSp1AAAEAwBIMEYCIQD+BdNUSUuhIlUwxjGObg0bfrea+z9PDYLyw7NQyxNu\n"
                             "mQIhAJ3a+kaoIYwJ5lJmCqGBljFmSr/n1rwfcHmCjeXqy6TQMAoGCCqGSM49BAMD\n"
                             "A2gAMGUCMGTMJlD3X43Jq4OSi67W6SGjcxE8EqX9hj1gMpCUXVAym+VfcPHmHJBh\n"
                             "cht/kXr+TwIxAM+xjo1vwTbJQ9rA+l0XyyzsT6WAqmepxMu+quntZs/uDD5i9dX0\n"
                             "GKLyZ/O9tWRpTg==\n"
                             "-----END CERTIFICATE-----\n"
                             "-----BEGIN CERTIFICATE-----\n"
                             "MIIEVjCCAj6gAwIBAgIQY5WTY8JOcIJxWRi/w9ftVjANBgkqhkiG9w0BAQsFADBP\n"
                             "MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy\n"
                             "Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yNDAzMTMwMDAwMDBa\n"
                             "Fw0yNzAzMTIyMzU5NTlaMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBF\n"
                             "bmNyeXB0MQswCQYDVQQDEwJFODB2MBAGByqGSM49AgEGBSuBBAAiA2IABNFl8l7c\n"
                             "S7QMApzSsvru6WyrOq44ofTUOTIzxULUzDMMNMchIJBwXOhiLxxxs0LXeb5GDcHb\n"
                             "R6EToMffgSZjO9SNHfY9gjMy9vQr5/WWOrQTZxh7az6NSNnq3u2ubT6HTKOB+DCB\n"
                             "9TAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMB\n"
                             "MBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFI8NE6L2Ln7RUGwzGDhdWY4j\n"
                             "cpHKMB8GA1UdIwQYMBaAFHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEB\n"
                             "BCYwJDAiBggrBgEFBQcwAoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzATBgNVHSAE\n"
                             "DDAKMAgGBmeBDAECATAnBgNVHR8EIDAeMBygGqAYhhZodHRwOi8veDEuYy5sZW5j\n"
                             "ci5vcmcvMA0GCSqGSIb3DQEBCwUAA4ICAQBnE0hGINKsCYWi0Xx1ygxD5qihEjZ0\n"
                             "RI3tTZz1wuATH3ZwYPIp97kWEayanD1j0cDhIYzy4CkDo2jB8D5t0a6zZWzlr98d\n"
                             "AQFNh8uKJkIHdLShy+nUyeZxc5bNeMp1Lu0gSzE4McqfmNMvIpeiwWSYO9w82Ob8\n"
                             "otvXcO2JUYi3svHIWRm3+707DUbL51XMcY2iZdlCq4Wa9nbuk3WTU4gr6LY8MzVA\n"
                             "aDQG2+4U3eJ6qUF10bBnR1uuVyDYs9RhrwucRVnfuDj29CMLTsplM5f5wSV5hUpm\n"
                             "Uwp/vV7M4w4aGunt74koX71n4EdagCsL/Yk5+mAQU0+tue0JOfAV/R6t1k+Xk9s2\n"
                             "HMQFeoxppfzAVC04FdG9M+AC2JWxmFSt6BCuh3CEey3fE52Qrj9YM75rtvIjsm/1\n"
                             "Hl+u//Wqxnu1ZQ4jpa+VpuZiGOlWrqSP9eogdOhCGisnyewWJwRQOqK16wiGyZeR\n"
                             "xs/Bekw65vwSIaVkBruPiTfMOo0Zh4gVa8/qJgMbJbyrwwG97z/PRgmLKCDl8z3d\n"
                             "tA0Z7qq7fta0Gl24uyuB05dqI5J1LvAzKuWdIjT1tP8qCoxSE/xpix8hX2dt3h+/\n"
                             "jujUgFPFZ0EVZ0xSyBNRF3MboGZnYXFUxpNjTWPKpagDHJQmqrAcDmWJnMsFY3jS\n"
                             "u1igv3OefnWjSQ==\n"
                             "-----END CERTIFICATE-----\n";
const unsigned int fullchain_pem_len = sizeof(fullchain_pem);